excludes:
  scopes:
    - pattern: "devDependencies"
      reason: "DEV_DEPENDENCY_OF"
      comment: "Packages for development only."
package_configurations:
- id: 'NPM::uri-js:4.4.1'
  source_artifact_url: "https://registry.npmjs.org/uri-js/-/uri-js-4.4.1.tgz"
  path_excludes:
  - pattern: "tests/**"
    reason: "TEST_OF"
    comment: "This directory contains tests only - this is not the preferred solution, but only an example how to use path_excludes"